-- ----------------------------
-- 2023.08.15增加动态字段功能，记得授权给你需要的角色
-- ----------------------------
-- ----------------------------
-- Records of DEV_DICT
-- ----------------------------
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1687104430738157570', '-1', '0', 'DFC类型', 'DFC_TYPE', 'FRM', '105', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1687104953432322049', '-1', '1687104430738157570', '输入框', 'input', 'FRM', '106', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1687105046696865793', '-1', '1687104430738157570', '数字输入框', 'number', 'FRM', '106', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1687521605483429890', '-1', '1687104430738157570', '多行文本', 'textarea', 'FRM', '106', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1688098040816222209', '-1', '1687104430738157570', '单选框', 'radio', 'FRM', '106', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1688130427063316481', '-1', '1687104430738157570', '多选框', 'checkbox', 'FRM', '106', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1688153828247154689', '-1', '1687104430738157570', '下拉选择', 'select', 'FRM', '106', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1688200409285578754', '-1', '1687104430738157570', '分页下拉选择', 'pageSelect', 'FRM', '106', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);

INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1688133068094910466', '-1', '0', 'DFC选择项类型', 'DFC_SELECT_OPTION_TYPE', 'FRM', '107', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1688133571604328450', '-1', '1688133068094910466', '字典', 'DICT', 'FRM', '108', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1688133651887501313', '-1', '1688133068094910466', '接口', 'API', 'FRM', '108', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);

-- ----------------------------
-- Table structure for DEV_DFC
-- ----------------------------
CREATE TABLE "SNOWY"."DEV_DFC"
(	"ID" NVARCHAR2(20) NOT NULL ENABLE,
     "TENANT_ID" NVARCHAR2(20),
     "DBS_ID" NVARCHAR2(20),
     "TABLE_NAME" NVARCHAR2(255),
     "SORT_CODE" NUMBER(11,0),
     "NAME" NVARCHAR2(255),
     "LABEL" NVARCHAR2(255),
     "REQUIRED" NUMBER(4,0),
     "PLACEHOLDER" NVARCHAR2(255),
     "TYPE" NVARCHAR2(255),
     "SELECT_OPTION_TYPE" NVARCHAR2(255),
     "DICT_TYPE_CODE" NVARCHAR2(255),
     "SEL_OPTION_API_URL" NVARCHAR2(255),
     "SEL_DATA_API_URL" NVARCHAR2(255),
     "IS_MULTIPLE" NUMBER(4,0),
     "DELETE_FLAG" NVARCHAR2(255),
     "CREATE_TIME" DATE,
     "CREATE_USER" NVARCHAR2(20),
     "UPDATE_TIME" DATE,
     "UPDATE_USER" NVARCHAR2(20)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"

COMMENT ON COLUMN "SNOWY"."DEV_DFC"."ID" IS '主键';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."TENANT_ID" IS '租户id';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."DBS_ID" IS '数据源';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."TABLE_NAME" IS '表名称';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."SORT_CODE" IS '排序码';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."NAME" IS '表单域属性名';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."LABEL" IS '标签文本';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."REQUIRED" IS '必填';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."PLACEHOLDER" IS '提示语';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."TYPE" IS '类型';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."SELECT_OPTION_TYPE" IS '选择项类型';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."DICT_TYPE_CODE" IS '字典';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."SEL_OPTION_API_URL" IS '选择项api地址';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."SEL_DATA_API_URL" IS '已选择数据api地址';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."IS_MULTIPLE" IS '是否多选';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."DELETE_FLAG" IS '删除标志';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."CREATE_USER" IS '创建用户';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "SNOWY"."DEV_DFC"."UPDATE_USER" IS '修改时间';

-- ----------------------------
-- Records of SYS_RESOURCE
-- ----------------------------
INSERT INTO "SNOWY"."SYS_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "NAME", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "COMPONENT", "ICON", "COLOR", "VISIBLE", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1687256714411425794', '-1', '1548901111999773250', '动态字段', 'dfc', 'j6ndvl7qyc', 'MENU', '1548901111999770525', 'MENU', '/dev/dfc', 'dev/dfc/index', 'chrome-filled', NULL, NULL, '99', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);