-- ----------------------------
-- 2023.02.10增加移动端管理的相关字典、菜单
-- ----------------------------
-- ----------------------------
-- Records of DEV_DICT
-- ----------------------------
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1619343323218432002', '-1', '0', '移动菜单状态', 'MOBILE_STATUS', 'FRM', '93', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1619343680636047362', '-1', '1619343323218432002', '可用', 'ENABLE', 'FRM', '94', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1619343846382358529', '-1', '1619343323218432002', '不可用', 'DISABLED', 'FRM', '96', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1619344256295882753', '-1', '0', '移动菜单规则', 'MOBILE_REG_TYPE', 'FRM', '97', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1619344428111351809', '-1', '1619344256295882753', '正规则', 'YES', 'FRM', '98', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."DEV_DICT"("ID", "TENANT_ID", "PARENT_ID", "DICT_LABEL", "DICT_VALUE", "CATEGORY", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1619344504456073218', '-1', '1619344256295882753', '反规则', 'NO', 'FRM', '99', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);

-- ----------------------------
-- Table structure for MOBILE_RESOURCE
-- ----------------------------
CREATE TABLE "SNOWY"."MOBILE_RESOURCE"
(	"ID" NVARCHAR2(20) NOT NULL ENABLE,
     "TENANT_ID" NVARCHAR2(20),
     "PARENT_ID" NVARCHAR2(255),
     "TITLE" NVARCHAR2(255),
     "CODE" NVARCHAR2(255),
     "CATEGORY" NVARCHAR2(255),
     "MODULE" NVARCHAR2(255),
     "MENU_TYPE" NVARCHAR2(255),
     "PATH" NVARCHAR2(255),
     "ICON" NVARCHAR2(255),
     "COLOR" NVARCHAR2(255),
     "REG_TYPE" NVARCHAR2(255),
     "STATUS" NVARCHAR2(255),
     "SORT_CODE" NUMBER(11,0),
     "EXT_JSON" NCLOB,
     "DELETE_FLAG" NVARCHAR2(255),
     "CREATE_TIME" DATE,
     "CREATE_USER" NVARCHAR2(20),
     "UPDATE_TIME" DATE,
     "UPDATE_USER" NVARCHAR2(20),
     CONSTRAINT "SYS_C0013013" PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SNOWY2.0"  ENABLE,
     CONSTRAINT "SYS_C0012985" CHECK ("ID" IS NOT NULL) ENABLE,
     CONSTRAINT "SYS_C0013281" CHECK ("ID" IS NOT NULL) ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("EXT_JSON") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))

COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."ID" IS '主键';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."TENANT_ID" IS '租户id';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."PARENT_ID" IS '父ID';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."TITLE" IS '名称';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."CODE" IS '编码';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."CATEGORY" IS '分类';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."MODULE" IS '模块';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."MENU_TYPE" IS '菜单类型';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."PATH" IS '路径';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."ICON" IS '图标';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."COLOR" IS '颜色';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."REG_TYPE" IS '规则类型';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."STATUS" IS '可用状态';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."SORT_CODE" IS '排序码';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."EXT_JSON" IS '扩展信息';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."DELETE_FLAG" IS '删除标志';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."CREATE_USER" IS '创建用户';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."UPDATE_TIME" IS '修改时间';
COMMENT ON COLUMN "SNOWY"."MOBILE_RESOURCE"."UPDATE_USER" IS '修改时间';

-- ----------------------------
-- Records of MOBILE_RESOURCE
-- ----------------------------
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623380023993298945', '-1', NULL, '业务', '217gcp9ifi', 'MODULE', NULL, NULL, NULL, 'container-outlined', '#1890ff', NULL, NULL, '1', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623380258656219138', '-1', '0', '机构管理', NULL, 'MENU', '1623380023993298945', 'MENU', '/pages/biz/org/index', 'apartment-outlined', '#1890ff', 'YES', 'ENABLE', '0', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623380614295449601', '-1', '0', '岗位管理', NULL, 'MENU', '1623380023993298945', 'MENU', '/pages/biz/position/index', 'robot-outlined', '#9c28b1', 'YES', 'ENABLE', '2', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623380765202313218', '-1', '0', '人员管理', NULL, 'MENU', '1623380023993298945', 'MENU', '/pages/biz/user/index', 'team-outlined', '#fed835', 'YES', 'ENABLE', '4', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623381127095250946', '-1', '0', '更多', NULL, 'MENU', '1623380023993298945', 'CATALOG', '7029146815941316608', 'small-dash-outlined', '#f1627e', 'YES', 'ENABLE', '7', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623381298801668098', '-1', '1623380258656219138', '新增机构', 'mobileBizOrgAdd', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623381632131395586', '-1', '1623380258656219138', '编辑机构', 'mobileBizOrgEdit', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623381698837606401', '-1', '1623380258656219138', '删除机构', 'mobileBizOrgDelete', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623696035909316610', '-1', '1623380614295449601', '新增岗位', 'mobileBizPositionAdd', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623696094872842242', '-1', '1623380614295449601', '编辑岗位', 'mobileBizPositionEdit', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623696153760870401', '-1', '1623380614295449601', '删除岗位', 'mobileBizPositionDelete', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623696236267024386', '-1', '1623380765202313218', '新增人员', 'mobileBizUserAdd', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623696292042878977', '-1', '1623380765202313218', '编辑人员', 'mobileBizUserEdit', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."MOBILE_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "ICON", "COLOR", "REG_TYPE", "STATUS", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623696346547859458', '-1', '1623380765202313218', '删除人员', 'mobileBizUserDelete', 'BUTTON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);

-- ----------------------------
-- Records of SYS_RESOURCE
-- ----------------------------
INSERT INTO "SNOWY"."SYS_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "NAME", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "COMPONENT", "ICON", "COLOR", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623378345382506498', '-1', '0', '移动端管理', NULL, NULL, 'MENU', '1548901111999770525', 'CATALOG', '/7029144034425704448', NULL, 'mobile-outlined', NULL, '50', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."SYS_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "NAME", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "COMPONENT", "ICON", "COLOR", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623378675591671810', '-1', '1623378345382506498', '模块管理', 'mobileModuleIndex', NULL, 'MENU', '1548901111999770525', 'MENU', '/mobile/module/index', 'mobile/resource/module/index', 'build-outlined', NULL, '51', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
INSERT INTO "SNOWY"."SYS_RESOURCE"("ID", "TENANT_ID", "PARENT_ID", "TITLE", "NAME", "CODE", "CATEGORY", "MODULE", "MENU_TYPE", "PATH", "COMPONENT", "ICON", "COLOR", "SORT_CODE", "EXT_JSON", "DELETE_FLAG", "CREATE_TIME", "CREATE_USER", "UPDATE_TIME", "UPDATE_USER") VALUES ('1623378996099411969', '-1', '1623378345382506498', '菜单管理', 'mobileMenuIndex', NULL, 'MENU', '1548901111999770525', 'MENU', '/mobile/menu/index', 'mobile/resource/menu/index', 'appstore-add-outlined', NULL, '52', NULL, 'NOT_DELETE', NULL, NULL, NULL, NULL);
