-- ----------------------------
-- 2023.12.25工作流关系表加5个通用字段
-- ----------------------------
ALTER TABLE "SNOWY"."ACT_EXT_RELATION"
    ADD ("DELETE_FLAG" NVARCHAR2(255))
ADD ("CREATE_TIME" DATE)
ADD ("CREATE_USER" NVARCHAR2(20))
ADD ("UPDATE_TIME" DATE)
ADD ("UPDATE_USER" NVARCHAR2(20));

COMMENT ON COLUMN "SNOWY"."ACT_EXT_RELATION"."DELETE_FLAG" IS '删除标志';

COMMENT ON COLUMN "SNOWY"."ACT_EXT_RELATION"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "SNOWY"."ACT_EXT_RELATION"."CREATE_USER" IS '创建用户';

COMMENT ON COLUMN "SNOWY"."ACT_EXT_RELATION"."UPDATE_TIME" IS '修改时间';

COMMENT ON COLUMN "SNOWY"."ACT_EXT_RELATION"."UPDATE_USER" IS '修改用户'